iso_code = "pl"
abbreviations = [
    "I cont",
    "R cont",
    "ags",
    "alb",
    "ang",
    "aor",
    "awest",
    "ba\u0142t",
    "bojkow",
    "bret",
    "brus",
    "bs\u0142",
    "bu\u0142g",
    "c.b.d.o",
    "c.b.d.u",
    "celt",
    "chorw",
    "cs",
    "czakaw",
    "czerw",
    "czes",
    "dniem",
    "dor",
    "dubrow",
    "du\u0144",
    "d\u0142u\u017c",
    "ekaw",
    "fi\u0144",
    "franc",
    "gal",
    "germ",
    "gniem",
    "goc",
    "gr",
    "grudz",
    "g\u0142u\u017c",
    "hebr",
    "het",
    "hol",
    "ie",
    "ikaw",
    "ira\u0144",
    "irl",
    "islandz",
    "itd",
    "itd.",
    "itp",
    "jekaw",
    "kajkaw",
    "kasz",
    "kirg",
    "kwiec",
    "lip",
    "listop",
    "lit",
    "lp",
    "maced",
    "mar",
    "moraw",
    "m\u0142pol",
    "n.e",
    "nb.",
    "ngr",
    "niem",
    "nord",
    "norw",
    "np",
    "np.",
    "ok.",
    "orm",
    "oset",
    "osk",
    "p.n",
    "p.n.e",
    "p.o",
    "pazdz",
    "pers",
    "pie",
    "pod red.",
    "podhal",
    "pol",
    "port",
    "po\u0142ab",
    "prekm",
    "pskow",
    "ps\u0142",
    "rez",
    "rom",
    "rozdz.",
    "rum",
    "rus",
    "rys.",
    "sas",
    "sch",
    "scs",
    "serb",
    "sierp",
    "sp. z o.o",
    "stbu\u0142g",
    "stind",
    "stpol",
    "stpr",
    "str.",
    "strus",
    "stwniem",
    "stycz",
    "sztokaw",
    "szwedz",
    "s\u0142a",
    "s\u0142e",
    "s\u0142i",
    "s\u0142ow",
    "t.",
    "tj.",
    "toch",
    "tur",
    "tzn",
    "t\u0142um.",
    "ukr",
    "ul",
    "umbr",
    "wed",
    "wlkpol",
    "wrzes",
    "wyd.",
    "w\u0119g",
    "w\u0142os",
    "zakarp",
    "\u0142ac",
    "\u0142ot",
    "\u015bl",
    "\u015brdniem",
    "\u015brgniem",
    "\u015brirl",
]
