iso_code = "de"
replace_all_abbr_periods = true
abbreviations = [
    "adj",
    "adm",
    "adv",
    "ao.univ.prof",
    "art",
    "ass",
    "ass.prof",
    "asst",
    "b.a",
    "b.s",
    "bart",
    "bldg",
    "brig",
    "bros",
    "bse",
    "buchst",
    "bzgl",
    "bzw",
    "c.-\u00e0-d",
    "ca",
    "capt",
    "chr",
    "cmdr",
    "co",
    "col",
    "comdr",
    "con",
    "corp",
    "cpl",
    "d.h",
    "d.j",
    "dergl",
    "dgl",
    "di",
    "dipl.-ing",
    "dkr",
    "dr",
    "ens",
    "etc",
    "ev",
    "evtl",
    "ff",
    "g.g.a",
    "g.u",
    "gen",
    "ggf",
    "gov",
    "hon",
    "hon.prof",
    "hosp",
    "i.f",
    "i.h.v",
    "ii",
    "iii",
    "insp",
    "iv",
    "ix",
    "jun",
    "k.o",
    "kath",
    "lfd",
    "lt",
    "ltd",
    "m.e",
    "mag",
    "maj",
    "med",
    "messrs",
    "mio",
    "mlle",
    "mm",
    "mme",
    "mr",
    "mrd",
    "mrs",
    "ms",
    "msgr",
    "mwst",
    "no",
    "nos",
    "nr",
    "o.univ.-prof",
    "o.\u00e4",
    "op",
    "ord",
    "pfc",
    "ph",
    "pp",
    "prof",
    "projektass",
    "pvt",
    "rep",
    "reps",
    "res",
    "rev",
    "rt",
    "s.p.a",
    "sa",
    "sen",
    "sens",
    "sfc",
    "sgt",
    "sog",
    "sogen",
    "spp",
    "sr",
    "st",
    "std",
    "str",
    "stud.ass",
    "supt",
    "surg",
    "u.a",
    "u.e",
    "u.s.w",
    "u.u",
    "u.\u00e4",
    "univ.-doz",
    "univ.-prof",
    "univ.ass",
    "usf",
    "usw",
    "v",
    "vgl",
    "vi",
    "vii",
    "viii",
    "vs",
    "x",
    "xi",
    "xii",
    "xiii",
    "xiv",
    "xix",
    "xv",
    "xvi",
    "xvii",
    "xviii",
    "xx",
    "z.b",
    "z.t",
    "z.z",
    "z.zt",
    "zt",
    "zzt",
    "\u00e4",
]
number_abbreviations = [
    "art",
    "ca",
    "no",
    "nos",
    "nr",
    "pp",
]
sentence_starters = [
    "Am",
    "Auch",
    "Auf",
    "Bei",
    "Da",
    "Das",
    "Der",
    "Die",
    "Ein",
    "Eine",
    "Es",
    "F\u00fcr",
    "Heute",
    "Ich",
    "Im",
    "In",
    "Ist",
    "Jetzt",
    "Mein",
    "Mit",
    "Nach",
    "So",
    "Und",
    "Warum",
    "Was",
    "Wenn",
    "Wer",
    "Wie",
    "Wir",
]
paired_punctuation_patterns = [
    "\\u201e(?=(?P<tmp>[^\\u201c\\\\]+|\\\\{2}|\\\\.)*)(?P=tmp)\\u201c",
    ",,(?=(?P<tmp>[^\\u201c\\\\]+|\\\\{2}|\\\\.)*)(?P=tmp)\\u201c",
]

[[rules]]
pattern = "(?<=Co)\\.(?=\\s*(?:KG|GmbH|OHG|AG)\\b)"
replacement = "\ue000"

[[rules]]
pattern = "(?<=\\d)\\.(?=\\s*(?:Januar|Februar|M\u00e4rz|April|Mai|Juni|Juli|August|September|Oktober|November|Dezember))"
replacement = "\ue000"

[[rules]]
pattern = "((?:(?<=^)|(?<=\\s))-?\\d{1,2})\\.(?=\\s)"
replacement = "\\g<1>\ue000"

[[rules]]
pattern = "((?:(?<=^)|(?<=\\s))[a-z])\\.(?=\\s)"
replacement = "\\g<1>\ue000"
