iso_code = "sk"
replace_all_abbr_periods = true
abbreviations = [
    "a. d",
    "a. g. p",
    "a. i. i",
    "a. k. a",
    "a. m",
    "a. r. k",
    "a. s",
    "a. s. a. p",
    "a. v",
    "a.d",
    "a.g.p",
    "a.i.i",
    "a.k.a",
    "a.m",
    "a.s",
    "a.s.a.p",
    "a.v",
    "akad",
    "al",
    "apod",
    "arm",
    "atd",
    "at\u010f",
    "at\u010f.",
    "bc",
    "bros",
    "c. k",
    "c.k",
    "cca",
    "co",
    "corp",
    "csc",
    "d. c",
    "d.c",
    "doc",
    "dr",
    "drsc",
    "e. t",
    "e.t",
    "el",
    "etc",
    "ev",
    "gen",
    "hl",
    "hod",
    "i. b",
    "i.b",
    "ii",
    "iii",
    "inc",
    "ind",
    "ing",
    "iv",
    "jr",
    "judr",
    "k. o",
    "k.o",
    "kol",
    "konkr",
    "kt",
    "ll. m",
    "ll.m",
    "m. n. m",
    "m.n.m",
    "m.o",
    "max",
    "mgr",
    "mil",
    "min",
    "ml",
    "mld",
    "mr",
    "mudr",
    "mvdr",
    "n. a",
    "n. o",
    "n. w. a",
    "n.a",
    "n.o",
    "n.w.a",
    "napr",
    "naprk",
    "nap\u0159",
    "ne\u0161p",
    "no",
    "nr",
    "n\u00e1m",
    "n\u00e1r",
    "o. c. p",
    "o. f. i",
    "o. k",
    "o. z",
    "o.c.p",
    "o.f.i",
    "o.i",
    "o.k",
    "o.z",
    "obr",
    "obv",
    "odd",
    "ods",
    "os",
    "p",
    "p. a",
    "p. n. l",
    "p. s",
    "p.a",
    "p.n.l",
    "p.s",
    "paeddr",
    "pedg",
    "ph. d",
    "ph.d",
    "phd",
    "phdr",
    "plgr",
    "pod",
    "pok",
    "pol. pr",
    "pol.pr",
    "por",
    "pozn",
    "pp",
    "pr",
    "prek",
    "prof",
    "pr\u00edp",
    "p\u00edsm",
    "r. o",
    "r.o",
    "red",
    "resp",
    "rndr",
    "roz",
    "rozh",
    "rsdr",
    "rtg",
    "s. a",
    "s. e. g",
    "s. r. o",
    "s.a",
    "s.e.g",
    "s.r.o",
    "skr",
    "sl",
    "slov",
    "soc",
    "sp",
    "spol",
    "sr",
    "st",
    "stor",
    "str",
    "stred",
    "sv",
    "sz",
    "s\u00fakr",
    "t. j",
    "t. z",
    "t. \u010d",
    "t.j",
    "t.z",
    "t.\u010d",
    "tel",
    "tis",
    "tj",
    "tr",
    "tu",
    "tvz",
    "tz",
    "tzn",
    "tzv",
    "u. s",
    "u.s",
    "ul",
    "v. sp",
    "v.sp",
    "var",
    "vi",
    "vi\u010f",
    "vs",
    "vyd",
    "vz",
    "xx",
    "z. z",
    "z.z",
    "zb",
    "zdravot",
    "zs",
    "zz",
    "z\u00e1k",
    "\u00fa. p. v. o",
    "\u00fa.p.v.o",
    "\u010d",
    "\u010ds",
    "\u010dsl",
    "\u0161. p",
    "\u0161.p",
    "\u0161t",
]
prepositive_abbreviations = [
    "bc",
    "doc",
    "dr",
    "drsc",
    "ing",
    "judr",
    "mgr",
    "mudr",
    "p",
    "prof",
    "st",
]
number_abbreviations = [
    "no",
    "nr",
    "\u010d",
]
paired_punctuation_patterns = [
    "\\u201e(?=(?P<tmp>[^\\u201c\\\\]+|\\\\{2}|\\\\.)*)(?P=tmp)\\u201c",
]

[[rules]]
pattern = "(?<=\\d)\\.(?=\\s*(?:Janu\u00e1r|Febru\u00e1r|Marec|Apr\u00edl|M\u00e1j|J\u00fan|J\u00fal|August|September|Okt\u00f3ber|November|December|Janu\u00e1ra|Febru\u00e1ra|Marca|Apr\u00edla|M\u00e1ja|J\u00fana|J\u00fala|Augusta|Septembra|Okt\u00f3bra|Novembra|Decembra))"
replacement = "\ue000"

[[rules]]
pattern = "(?<=\\d)\\.(?=\\s*[a-z]+)"
replacement = "\ue000"

[[rules]]
pattern = "((?:(?<=^)|(?<=\\s))[VXI]+)\\.(?=\\s+)"
replacement = "\\g<1>\ue000"
